var annotated_dup =
[
    [ "Application", "classApplication.html", "classApplication" ],
    [ "BasicFilter", "classBasicFilter.html", "classBasicFilter" ],
    [ "BMPImage", "classBMPImage.html", "classBMPImage" ],
    [ "BufferedFrame", "classBufferedFrame.html", "classBufferedFrame" ],
    [ "Color", "classColor.html", "classColor" ],
    [ "DataSource", "classDataSource.html", "classDataSource" ],
    [ "DataSourceFactory", "classDataSourceFactory.html", "classDataSourceFactory" ],
    [ "error_mgr", "structerror__mgr.html", "structerror__mgr" ],
    [ "FileManager", "classFileManager.html", "classFileManager" ],
    [ "FileMenu", "classFileMenu.html", "classFileMenu" ],
    [ "Filter", "classFilter.html", "classFilter" ],
    [ "Frame", "classFrame.html", "classFrame" ],
    [ "Gallery", "classGallery.html", "classGallery" ],
    [ "Image", "classImage.html", "classImage" ],
    [ "JPEGImage", "classJPEGImage.html", "classJPEGImage" ],
    [ "Logger", "classLogger.html", "classLogger" ],
    [ "Matrix", "classMatrix.html", "classMatrix" ],
    [ "Menu", "classMenu.html", "classMenu" ],
    [ "PNGImage", "classPNGImage.html", "classPNGImage" ],
    [ "Settings", "classSettings.html", "classSettings" ],
    [ "Test", "classTest.html", "classTest" ],
    [ "TestFileManager", "classTestFileManager.html", "classTestFileManager" ],
    [ "TestMatrix", "classTestMatrix.html", "classTestMatrix" ],
    [ "TestVector", "classTestVector.html", "classTestVector" ],
    [ "Vector", "structVector.html", "structVector" ],
    [ "Video", "classVideo.html", "classVideo" ]
];